PREFIX   ?= /usr/local
BINDIR    = ${PREFIX}/bin
LIBDIR    = ${PREFIX}/lib
MANDIR    = ${PREFIX}/man
FILESDIR  = ${PREFIX}/share/misc

PROG      = kol_editor
SRCS      =
MAN       =

.include <bsd.prog.mk>
